### ISSUE TITLE
Como passar parâmetro pelo botão fieldlist

### ISSUE THREAD

**Issue by cortezfelipe** [cortezfelipe/tutor7#5]
No botão adicionar o objeto js e enviar pela URL

"const obj = JSON.parse(JSON.stringify(tfieldlist_get_row_data(this))); 
__adianti_post_data('form_Produto', 'class=ProdutoForm&method=exibirOpcionalSelecionado&item=' + obj.list_opcionais);"

**Comment by cadumicro** [comment]
> No botão adicionar o objeto js e enviar pela URL
> 
> "const obj = JSON.parse(JSON.stringify(tfieldlist_get_row_data(this)));
> __adianti_post_data('form_Produto', 'class=ProdutoForm&method=exibirOpcionalSelecionado&item=' + obj.list_opcionais);"

Complementando o exemplo:

/* Método para retornar a linha corrente de um TFieldList */
function tfieldlist_get_row(e) {
    var t = {};
    t.index = $(e).closest("tr").index();
    $(e).closest("tr").find("[name]").each(function(e, n) {
        var a = $(n).attr("name");
        a = a.replace("[]", "");
        //console.log(a);
        if(a == 'text'){
        console.log($(n).val());
        t[a] = $(n).val();
        }
    });
    return t
}
// Adicionando button function ao FieldList

// Método JS
// 1  - Obtém o obj com a linha selecionada
//   const obj = JSON.parse(JSON.stringify(tfieldlist_get_row_data(this)));  

// 2 - Executa método passando o valor para método da page
//__adianti_post_data('form_cadastro','class=CadastroForm&method=linhaFieldListSelecionada&valor//+ obj.list_opcionais);

// Exemplo de uso
$this->FieldList->addButtonFunction(" const obj = JSON.parse(JSON.stringify(tfieldlist_get_row_data(this)));  
									  __adianti_post_data('form_cadastro', 'class=CadastroForm&method=linhaFieldListSelecionada&valor=' + obj.list_campo);", 
								    'fa:info-circle blue', 'Item Selecionado');

**Comment by cortezfelipe** [comment]
topico encerrado
